version: "3.9"

services:
  app:
    build: .
    container_name: "app-${PR_ID}"    # уникальное имя контейнера
    ports:
      - "${PORT}:8080"                # порт из переменной
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
