services:
  app:
    build: .
    container_name: "app-${PR_ID}"
    ports:
      - "${PR_PORT}:8080"   # Внешний порт = PR_PORT
    environment:
      - PORT=8080           # Внутренний порт контейнера
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
