services:
  app:
    build: .
    container_name: "app-${PR_ID}"
    ports:
      - "${PR_PORT}:8080"   # Динамический проброс порта
    environment:
      - PORT=8080           # Порт внутри контейнера
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
