version: "3.9"

services:
  app:
    build: .
    # container_name убрали
    ports:
      - "${PORT:-8080}:8080"  # динамический порт через переменную PORT, по умолчанию 8080
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
